package hpi

// Type of Transform functions

const HPI_TType_MergeString = "merge_string"
const HPI_TType_SplitString = "split_string"
const HPI_TType_SplitStringArray = "split_string_array"
const HPI_TType_ReplaceString = "replace_string"
const HPI_TType_TrimString = "trim_string"
const HPI_TType_GenUUID = "gen_uuid"
const HPI_TType_GenUniqueId = "gen_uniqueId"
const HPI_TType_RandomInteger = "random_int"
const HPI_TType_RandomAlphabet = "random_alphabet"
const HPI_TType_GetCurrentTime = "get_current_time"
const HPI_TType_RenameFields = "rename_fields"

const HPI_TType_DateFormat = "date_format"
const HPI_TType_NumberFormat = "number_format"
const HPI_TType_IncreaseNum = "increase_num"
const HPI_TType_DecreaseNum = "decrease_num"
const HPI_TType_ToNumber = "to_number"
const HPI_TType_ToBoolean = "to_boolean"
const HPI_TType_FixValue = "fix_value"
const HPI_TType_DeleteField = "delete_field"
const HPI_TType_GetKeysInMap = "get_keys_in_map"
const HPI_TType_GetValuesInMap = "get_values_in_map"
const HPI_TType_CheckValue = "check_value"
const HPI_TType_NameFormat = "name_format"
const HPI_TType_TimeStampToDate = "timestamp_to_date"
const HPI_TType_DateToTimeStamp = "date_to_timestamp"
const HPI_TType_GetCurrentTimeStamp = "get_current_timestamp"

const HPI_TType_ListSize = "list_size"
const HPI_TType_AddToList = "add_to_list"
const HPI_TType_AddObjectToList = "add_object_to_list"
const HPI_TType_UpdateRecord = "update_record"
const HPI_TType_CopyToList = "copy_to_list"
const HPI_TType_CopyFromList = "copy_from_list"
const HPI_TType_CopyFromListToObject = "copy_from_list_to_object"
const HPI_TType_JoinList = "join_list"
const HPI_TType_DeleteRecord = "delete_record"
const HPI_TType_FilterRecord = "filter_record"
const HPI_TType_FindOneRecord = "find_one_record"
const HPI_TType_SumFieldsInList = "sum_fields_in_list"
const HPI_TType_SearchValueInList = "search_value_in_list"
const HPI_TType_SplitListToObject = "split_list_to_object"

const HPI_TType_CalculateNumber = "calculate_number"
const HPI_TType_MathUtil = "math_util"
const HPI_TType_CompareNumber = "compare_number"
const HPI_TType_CompareString = "compare_string"
const HPI_TType_CompareDateTime = "compare_date_time"
const HPI_TType_CopyObjectToSameParent = "copy_object_to_same_parent"
const HPI_TType_ValidateAndCopy = "validate_and_copy"
const HPI_TType_SortList = "sort_list"
const HPI_TType_CheckExistingField = "check_existing_field"

const HPI_TType_FindValuesByRegExp = "find_values_by_regexp"
const HPI_TType_ModifyString = "modify_string"

const HPI_TType_Base64Encode = "base64_encode"
const HPI_TType_Base64Decode = "base64_decode"
const HPI_TType_Aes256GcmEncode = "aes256gcm_encode"
const HPI_TType_Aes256GcmDecode = "aes256gcm_decode"

const HPI_TType_JsonToString = "json_to_string"
const HPI_TType_StringToJson = "string_to_json"

const HPI_TType_SsqToDma = "ssq_to_dma"
const HPI_TType_DmaToSsq = "dma_to_ssq"
